### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by konsumer** [jfirebaugh/node-debug#7]
I get this in node v7.2.0 when I try to run `node-debug myscript.js`:

```
/usr/local/lib/node_modules/node-debug/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/node-debug/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-debug/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)
```

**Comment by jfirebaugh** [comment]
This module is obsolete and shouldn't be used; see [README.md](https://github.com/jfirebaugh/node-debug/blob/master/README.md).
